/* Data pour les platsPopulaires */

export const data = [
	{
		id: 1,
		image: '../../public/images/pouletpane.jpg',
    alt : 'poulet-pane',
		title: 'Poulet Pane',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 12000,
	},
	{
		id: 2,
		image: '../../public/images/chocolat.jpg',
    alt : 'chocolat',
		title: 'Framboise au Chocolat',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 5000,
	},
	{
		id: 3,
		image: '../../public/images/biscuit.jpg',
    alt : 'biscuit',
		title: 'Savour de Biscuit',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 500,
	},
	{
		id: 4,
		image: '../../public/images/HamBurger.jpg',
    alt : 'hamurger',
		title: 'HamBurger',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 2000,
	},
	{
		id: 5,
		image: '../../public/images/Pouletdg.jpg',
    alt : 'poulet-dg',
		title: 'Poulet DG',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 10000,
	},
	{
		id: 6,
    image: '../../public/images/fritepomme.jpg',
    alt : 'pomme-frite',
		title: 'Pomme Frite',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 2000,
	},
	{
		id: 7,
    image: '../../public/images/pommepile.jpg',
    alt : 'pomme pile',
		title: 'Pomme Pile',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 2000,
	},
	{
		id: 8,
    image: '../../public/images/malaxé.jpg',
    alt : 'malaxé',
		title: 'Banane malaxé',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 5000,
	},
	{
		id: 9,
    image: '../../public/images/saucejaune.jpg',
    alt : 'Taro Sauce Jaune',
		title: 'Taro Sauce Jaune',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 5000,
	},
	{
		id: 10,
    image: '../../public/images/kwui.jpg',
    alt : 'kwui',
		title: ' Le Kwui',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 3500,
	},
	{
		id: 11,
    image: '../../public/images/couscousLegumes.jfif',
    alt : 'couscous legume',
		title: 'Couscous Legume',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 10000,
	},
	{
		id: 12,
    image: '../../public/images/okok.jpg',
    alt : 'okok',
		title: 'L\'Okok',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, ex?',
		prix: 2000,
	},
];

